export enum RugbyPositions {
  LOOSE_HEAD_PROP = '1',
  HOOKER = '2',
  TIGHT_HEAD_PROP = '3',
  LEFT_SECOND_ROW = '4',
  RIGHT_SECOND_ROW = '5',
  BLINDSIDE_FLANKER = '6',
  OPEN_SIDE_FLANKER = '7',
  NUMBER_8 = '8',
  SCRUM_HALF = '9',
  FLY_HALF = '10',
  LEFT_WING = '11',
  INSIDE_CENTRE = '12',
  OUTSIDE_CENTRE = '13',
  RIGHT_WING = '14',
  FULLBACK = '15',
}

export enum HockeyPositions {
  GOALKEEPER = '1',
  LIBERO = '2',
  STOPPER = '3',
  RIGHT_BACK = '4',
  LEFT_BACK = '5',
  CENTRAL_MID = '6',
  RIGHT_INTERIOR = '7',
  LEFT_INTERIOR = '8',
  RIGHT_WING = '9',
  LEFT_WING = '10',
  CENTER_FORWARD = '11',
}
